const categories: { name: string; description: string }[] = [
  { name: 'Open Source', description: 'Tools related to open source development.' },
  { name: 'DevOps', description: 'Tools for optimizing and automating the software development lifecycle.' },
  { name: 'AI', description: 'Artificial Intelligence and Machine Learning tools.' },
  { name: 'CI', description: 'Continuous Integration tools for automated testing and deployment.' },
  { name: 'Code', description: 'Tools related to coding and programming.' },
  { name: 'NoCode', description: 'Tools that allow building applications without coding.' },
  { name: 'Analytics', description: 'Tools for collecting and analyzing data.' },
  { name: 'QA', description: 'Quality Assurance and testing tools.' },
  { name: 'API', description: 'Tools for working with APIs (Application Programming Interfaces).' },
  { name: 'DB', description: 'Database management tools and frameworks.' },
  { name: 'Design', description: 'Tools for graphic and user interface design.' },
  { name: 'Helpers', description: 'Various helper tools for developers.' },
  { name: 'Hosting', description: 'Services and platforms for hosting applications and websites.' },
  { name: 'UI Library', description: 'User Interface component libraries and frameworks.' },
  { name: 'Marketing', description: 'Tools for marketing and promoting products.' },
  { name: 'Emails', description: 'Email marketing and communication tools.' },
  { name: 'Framework', description: 'Development frameworks for building applications.' },
  { name: 'Language', description: 'Programming languages and related tools.' },
  { name: 'Crypto', description: 'Cryptocurrency and blockchain-related tools.' },
  { name: 'Web3', description: 'Web3 development tools for decentralized applications.' },
  { name: 'Charts', description: 'Charting and visualization libraries.' },
  { name: 'IDE', description: 'Integrated Development Environments for coding.' },
  { name: 'Monitoring', description: 'Tools for monitoring and observability.' },
  { name: 'Workflow automation', description: 'Automation tools for workflows and processes.' },
  { name: 'CMS', description: 'Content Management Systems for building and managing websites.' },
  { name: 'Security', description: 'Security tools and practices for protecting applications.' },
  { name: 'Tailwind CSS', description: 'Utility-first CSS framework.' },
  { name: 'Boilerplate', description: 'Starter code templates for new projects.' },
];

export default categories;
