const categories: { name: string; description: string }[] = [
  { name: 'Open Source', description: 'Tools related to open source development.' },
  { name: 'DevOps', description: 'Tools for optimizing and automating the software development lifecycle.' },
  { name: 'AI', description: 'Artificial Intelligence and Machine Learning tools.' },
  { name: 'CI', description: 'Continuous Integration tools for automated testing and deployment.' },
  { name: 'Code', description: 'Tools related to coding and programming.' },
  { name: 'NoCode', description: 'Tools that allow building applications without coding.' },
  { name: 'Analytics', description: 'Tools for collecting and analyzing data.' },
  { name: 'QA', description: 'Quality Assurance and testing tools.' },
  { name: 'API', description: 'Tools for working with APIs (Application Programming Interfaces).' },
  { name: 'DB', description: 'Database management tools and frameworks.' },
  { name: 'Design', description: 'Tools for graphic and user interface design.' },
  { name: 'Helpers', description: 'Various helper tools for developers.' },
  { name: 'Hosting', description: 'Services and platforms for hosting applications and websites.' },
  { name: 'UI Library', description: 'User Interface component libraries and frameworks.' },
  { name: 'Marketing', description: 'Tools for marketing and promoting products.' },
  { name: 'Emails', description: 'Email marketing and communication tools.' },
  { name: 'Framework', description: 'Development frameworks for building applications.' },
  { name: 'Language', description: 'Programming languages and related tools.' },
  { name: 'Crypto', description: 'Cryptocurrency and blockchain-related tools.' },
  { name: 'Web3', description: 'Web3 development tools for decentralized applications.' },
  { name: 'Charts', description: 'Charting and visualization libraries.' },
  { name: 'IDE', description: 'Integrated Development Environments for coding.' },
  { name: 'Monitoring', description: 'Tools for monitoring and observability.' },
  { name: 'Workflow automation', description: 'Automation tools for workflows and processes.' },
  { name: 'CMS', description: 'Content Management Systems for building and managing websites.' },
  { name: 'Security', description: 'Security tools and practices for protecting applications.' },
  { name: 'Tailwind CSS', description: 'Utility-first CSS framework.' },
  { name: 'Boilerplate', description: 'Starter code templates for new projects.' },
  { name: 'CLI', description: 'Command-line tools for developers.' },
  { name: 'Visual editing', description: 'Visual editors and drag-and-drop builders.' },
  { name: 'SEO', description: 'Tools for search engine optimization, keywords and backlinks.' },
  { name: 'AI Agents', description: 'Autonomous AI agents and agent frameworks.' },
  { name: 'AI Coding', description: 'AI coding assistants, coding agents, AI code review and tools that make them work better.' },
  { name: 'MCP', description: 'Model Context Protocol servers, clients and directories.' },
  { name: 'Testing', description: 'Unit, end-to-end, load and API testing tools.' },
  { name: 'Mobile', description: 'Tools for building iOS and Android apps.' },
  { name: 'Browser Extension', description: 'Chrome, Firefox and other browser extensions.' },
  { name: 'Auth', description: 'Authentication, SSO and user management.' },
  { name: 'Payments', description: 'Payments, billing and subscription tools.' },
  { name: 'Content Writing', description: 'AI writing, copywriting and blog content tools.' },
  { name: 'Image', description: 'Image generation and editing tools.' },
  { name: 'Video', description: 'Video generation, editing and screen recording tools.' },
  { name: 'Voice', description: 'Voice, speech and audio tools.' },
  { name: 'Social Media', description: 'Tools for social media posting and growth.' },
  { name: 'Sales', description: 'CRM, lead generation and outreach tools.' },
  { name: 'Docs', description: 'Documentation and knowledge base tools.' },
  { name: 'Other', description: 'Useful products that are not developer tools.' },
];

export default categories;
