// Tools used to get an auto-generated paracast.io promo video when no demo video was given.
// Those links are slow or broken, so they are treated as "no video".
export const isAutoGeneratedVideo = (url?: string | null) => !!url && url.includes('paracast.io');

export const usableVideoUrl = (url?: string | null) => (url && !isAutoGeneratedVideo(url) ? url : undefined);
