// Well-known tools DevHunt lists itself (products.is_reference), so category pages aren't missing the tools
// developers expect (Cursor, Claude Code, Codex, Supabase...). Seeded by scripts/seed-reference-tools.ts:
// the website is scraped for the description, logo and screenshot, then a profile is generated.
// Slogans are short and factual; pricing: 1 free, 2 subscription, 3 one-time (the model most people pay with).

export interface ReferenceTool {
  name: string;
  url: string;
  slogan: string;
  pricing: 1 | 2 | 3;
  categories: string[]; // names from utils/categories.ts
  githubUrl?: string;
}

export const REFERENCE_TOOLS: ReferenceTool[] = [
  // AI coding
  { name: 'Cursor', url: 'https://cursor.com', slogan: 'The AI code editor', pricing: 2, categories: ['AI Coding', 'IDE'] },
  {
    name: 'Claude Code',
    url: 'https://www.anthropic.com/claude-code',
    slogan: "Anthropic's agentic coding tool for the terminal and IDE",
    pricing: 2,
    categories: ['AI Coding', 'CLI', 'AI Agents'],
  },
  {
    name: 'OpenAI Codex',
    url: 'https://openai.com/codex/',
    slogan: "OpenAI's coding agent for the terminal, IDE and cloud",
    pricing: 2,
    categories: ['AI Coding', 'AI Agents'],
  },
  {
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    slogan: 'AI pair programmer in your editor and on GitHub',
    pricing: 2,
    categories: ['AI Coding'],
  },
  {
    name: 'Windsurf',
    url: 'https://windsurf.com',
    slogan: 'AI-native code editor with an agent built in',
    pricing: 2,
    categories: ['AI Coding', 'IDE'],
  },
  {
    name: 'Cline',
    url: 'https://cline.bot',
    slogan: 'Open-source autonomous coding agent for your IDE',
    pricing: 1,
    categories: ['AI Coding', 'Open Source'],
    githubUrl: 'https://github.com/cline/cline',
  },
  {
    name: 'Aider',
    url: 'https://aider.chat',
    slogan: 'AI pair programming in your terminal',
    pricing: 1,
    categories: ['AI Coding', 'CLI', 'Open Source'],
    githubUrl: 'https://github.com/Aider-AI/aider',
  },
  {
    name: 'Gemini CLI',
    url: 'https://github.com/google-gemini/gemini-cli',
    slogan: "Google's open-source AI agent for the terminal",
    pricing: 1,
    categories: ['AI Coding', 'CLI', 'Open Source'],
    githubUrl: 'https://github.com/google-gemini/gemini-cli',
  },
  { name: 'Devin', url: 'https://devin.ai', slogan: 'Autonomous AI software engineer', pricing: 2, categories: ['AI Coding', 'AI Agents'] },
  {
    name: 'Tabnine',
    url: 'https://www.tabnine.com',
    slogan: 'AI code assistant for teams and enterprises',
    pricing: 2,
    categories: ['AI Coding'],
  },
  {
    name: 'Zed',
    url: 'https://zed.dev',
    slogan: 'High-performance code editor with AI built in',
    pricing: 1,
    categories: ['IDE', 'Open Source', 'AI Coding'],
    githubUrl: 'https://github.com/zed-industries/zed',
  },
  {
    name: 'Lovable',
    url: 'https://lovable.dev',
    slogan: 'Build apps and websites by chatting with AI',
    pricing: 2,
    categories: ['AI Coding', 'NoCode'],
  },
  {
    name: 'Bolt',
    url: 'https://bolt.new',
    slogan: 'Prompt, run, edit and deploy full-stack web apps',
    pricing: 2,
    categories: ['AI Coding', 'NoCode'],
  },
  { name: 'v0', url: 'https://v0.app', slogan: "Vercel's AI app and UI builder", pricing: 2, categories: ['AI Coding', 'Design'] },
  {
    name: 'Replit',
    url: 'https://replit.com',
    slogan: 'Build and deploy software with AI, in the browser',
    pricing: 2,
    categories: ['AI Coding', 'IDE', 'Hosting'],
  },
  // APIs
  {
    name: 'Postman',
    url: 'https://www.postman.com',
    slogan: 'API platform for designing, testing and documenting APIs',
    pricing: 2,
    categories: ['API', 'Testing'],
  },
  {
    name: 'Insomnia',
    url: 'https://insomnia.rest',
    slogan: 'Open-source API client for REST, GraphQL and gRPC',
    pricing: 1,
    categories: ['API', 'Open Source'],
    githubUrl: 'https://github.com/Kong/insomnia',
  },
  {
    name: 'Bruno',
    url: 'https://www.usebruno.com',
    slogan: 'Offline-first, Git-friendly open-source API client',
    pricing: 1,
    categories: ['API', 'Open Source'],
    githubUrl: 'https://github.com/usebruno/bruno',
  },
  // Backends and databases
  {
    name: 'Supabase',
    url: 'https://supabase.com',
    slogan: 'Open-source Postgres development platform',
    pricing: 2,
    categories: ['DB', 'Auth', 'Open Source'],
    githubUrl: 'https://github.com/supabase/supabase',
  },
  {
    name: 'Firebase',
    url: 'https://firebase.google.com',
    slogan: "Google's platform to build and run apps",
    pricing: 2,
    categories: ['DB', 'Auth', 'Hosting'],
  },
  { name: 'Neon', url: 'https://neon.com', slogan: 'Serverless Postgres', pricing: 2, categories: ['DB'] },
  {
    name: 'Appwrite',
    url: 'https://appwrite.io',
    slogan: 'Open-source backend for web and mobile apps',
    pricing: 2,
    categories: ['DB', 'Auth', 'Open Source'],
    githubUrl: 'https://github.com/appwrite/appwrite',
  },
  {
    name: 'PocketBase',
    url: 'https://pocketbase.io',
    slogan: 'Open-source backend in one file',
    pricing: 1,
    categories: ['DB', 'Open Source'],
    githubUrl: 'https://github.com/pocketbase/pocketbase',
  },
  // Hosting and DevOps
  {
    name: 'Vercel',
    url: 'https://vercel.com',
    slogan: 'Frontend cloud to build and deploy web apps',
    pricing: 2,
    categories: ['Hosting', 'DevOps'],
  },
  {
    name: 'Netlify',
    url: 'https://www.netlify.com',
    slogan: 'Platform to build and deploy web projects',
    pricing: 2,
    categories: ['Hosting', 'DevOps'],
  },
  {
    name: 'Railway',
    url: 'https://railway.com',
    slogan: 'Deploy apps, databases and services',
    pricing: 2,
    categories: ['Hosting', 'DevOps'],
  },
  {
    name: 'Render',
    url: 'https://render.com',
    slogan: 'Cloud to build, deploy and scale apps',
    pricing: 2,
    categories: ['Hosting', 'DevOps'],
  },
  { name: 'Fly.io', url: 'https://fly.io', slogan: 'Run full-stack apps close to your users', pricing: 2, categories: ['Hosting'] },
  {
    name: 'Cloudflare Workers',
    url: 'https://workers.cloudflare.com',
    slogan: "Serverless code on Cloudflare's global network",
    pricing: 2,
    categories: ['Hosting'],
  },
  { name: 'Docker', url: 'https://www.docker.com', slogan: 'Build, share and run containers', pricing: 2, categories: ['DevOps'] },
  {
    name: 'GitHub Actions',
    url: 'https://github.com/features/actions',
    slogan: 'CI/CD and automation built into GitHub',
    pricing: 2,
    categories: ['CI', 'DevOps'],
  },
  {
    name: 'Datadog',
    url: 'https://www.datadoghq.com',
    slogan: 'Monitoring and security platform for cloud apps',
    pricing: 2,
    categories: ['Monitoring'],
  },
  // Auth, payments, docs
  { name: 'Auth0', url: 'https://auth0.com', slogan: 'Authentication and authorization platform', pricing: 2, categories: ['Auth'] },
  {
    name: 'Stripe',
    url: 'https://stripe.com',
    slogan: 'Payments infrastructure for the internet',
    pricing: 2,
    categories: ['Payments', 'API'],
  },
  {
    name: 'Notion',
    url: 'https://www.notion.com',
    slogan: 'Connected workspace for docs, wikis and projects',
    pricing: 2,
    categories: ['Docs'],
  },
  // UI
  {
    name: 'shadcn/ui',
    url: 'https://ui.shadcn.com',
    slogan: 'Open-source React components you copy into your app',
    pricing: 1,
    categories: ['UI Library', 'Open Source'],
    githubUrl: 'https://github.com/shadcn-ui/ui',
  },
  {
    name: 'Tailwind CSS',
    url: 'https://tailwindcss.com',
    slogan: 'Utility-first CSS framework',
    pricing: 1,
    categories: ['Tailwind CSS', 'Framework', 'Open Source'],
    githubUrl: 'https://github.com/tailwindlabs/tailwindcss',
  },
  // AI agents and automation
  {
    name: 'LangChain',
    url: 'https://www.langchain.com',
    slogan: 'Framework for building LLM apps and agents',
    pricing: 1,
    categories: ['AI Agents', 'Framework', 'Open Source'],
    githubUrl: 'https://github.com/langchain-ai/langchain',
  },
  {
    name: 'CrewAI',
    url: 'https://www.crewai.com',
    slogan: 'Framework and platform for multi-agent AI systems',
    pricing: 2,
    categories: ['AI Agents', 'Open Source'],
    githubUrl: 'https://github.com/crewAIInc/crewAI',
  },
  {
    name: 'n8n',
    url: 'https://n8n.io',
    slogan: 'Workflow automation with AI, cloud or self-hosted',
    pricing: 2,
    categories: ['Workflow automation', 'AI Agents'],
    githubUrl: 'https://github.com/n8n-io/n8n',
  },
  // Analytics
  {
    name: 'PostHog',
    url: 'https://posthog.com',
    slogan: 'Product analytics, session replay and feature flags',
    pricing: 2,
    categories: ['Analytics', 'Open Source'],
    githubUrl: 'https://github.com/PostHog/posthog',
  },
  {
    name: 'Plausible',
    url: 'https://plausible.io',
    slogan: 'Privacy-friendly, open-source web analytics',
    pricing: 2,
    categories: ['Analytics', 'Open Source'],
    githubUrl: 'https://github.com/plausible/analytics',
  },
  // Batch 2 (2026-10-01): peers for batch 1, so every listing has real alternatives
  // Payments
  {
    name: 'Paddle',
    url: 'https://www.paddle.com',
    slogan: 'Merchant of record for SaaS payments, tax and subscriptions',
    pricing: 2,
    categories: ['Payments'],
  },
  {
    name: 'Lemon Squeezy',
    url: 'https://www.lemonsqueezy.com',
    slogan: 'Payments, tax and subscriptions for software',
    pricing: 2,
    categories: ['Payments'],
  },
  {
    name: 'Polar',
    url: 'https://polar.sh',
    slogan: 'Open-source payments and billing for developers',
    pricing: 2,
    categories: ['Payments', 'Open Source'],
    githubUrl: 'https://github.com/polarsource/polar',
  },
  // CI, containers, infrastructure
  {
    name: 'GitLab CI',
    url: 'https://about.gitlab.com/solutions/continuous-integration/',
    slogan: 'CI/CD pipelines built into GitLab',
    pricing: 2,
    categories: ['CI', 'DevOps'],
  },
  {
    name: 'CircleCI',
    url: 'https://circleci.com',
    slogan: 'CI/CD platform for building, testing and deploying',
    pricing: 2,
    categories: ['CI', 'DevOps'],
  },
  {
    name: 'Podman',
    url: 'https://podman.io',
    slogan: 'Daemonless, open-source container engine',
    pricing: 1,
    categories: ['DevOps', 'Open Source'],
    githubUrl: 'https://github.com/containers/podman',
  },
  {
    name: 'Kubernetes',
    url: 'https://kubernetes.io',
    slogan: 'Open-source container orchestration',
    pricing: 1,
    categories: ['DevOps', 'Open Source'],
    githubUrl: 'https://github.com/kubernetes/kubernetes',
  },
  {
    name: 'Terraform',
    url: 'https://developer.hashicorp.com/terraform',
    slogan: 'Infrastructure as code for any cloud',
    pricing: 1,
    categories: ['DevOps'],
  },
  {
    name: 'Coolify',
    url: 'https://coolify.io',
    slogan: 'Open-source, self-hostable alternative to Heroku and Vercel',
    pricing: 1,
    categories: ['Hosting', 'DevOps', 'Open Source'],
    githubUrl: 'https://github.com/coollabsio/coolify',
  },
  // Analytics
  {
    name: 'Mixpanel',
    url: 'https://mixpanel.com',
    slogan: 'Product analytics for events, funnels and retention',
    pricing: 2,
    categories: ['Analytics'],
  },
  {
    name: 'Amplitude',
    url: 'https://amplitude.com',
    slogan: 'Digital analytics platform for product teams',
    pricing: 2,
    categories: ['Analytics'],
  },
  {
    name: 'Google Analytics',
    url: 'https://marketingplatform.google.com/about/analytics/',
    slogan: "Google's web and app analytics",
    pricing: 1,
    categories: ['Analytics'],
  },
  {
    name: 'Umami',
    url: 'https://umami.is',
    slogan: 'Simple, privacy-focused, open-source web analytics',
    pricing: 1,
    categories: ['Analytics', 'Open Source'],
    githubUrl: 'https://github.com/umami-software/umami',
  },
  // Monitoring
  {
    name: 'Grafana',
    url: 'https://grafana.com',
    slogan: 'Open-source dashboards and observability',
    pricing: 2,
    categories: ['Monitoring', 'Open Source'],
    githubUrl: 'https://github.com/grafana/grafana',
  },
  {
    name: 'New Relic',
    url: 'https://newrelic.com',
    slogan: 'Observability platform for apps and infrastructure',
    pricing: 2,
    categories: ['Monitoring'],
  },
  {
    name: 'Better Stack',
    url: 'https://betterstack.com',
    slogan: 'Uptime monitoring, incidents, logs and status pages',
    pricing: 2,
    categories: ['Monitoring'],
  },
  // Databases
  {
    name: 'PlanetScale',
    url: 'https://planetscale.com',
    slogan: 'Hosted MySQL and Postgres built for scale',
    pricing: 2,
    categories: ['DB'],
  },
  {
    name: 'MongoDB',
    url: 'https://www.mongodb.com',
    slogan: 'Document database, self-hosted or as Atlas in the cloud',
    pricing: 2,
    categories: ['DB'],
  },
  {
    name: 'Convex',
    url: 'https://www.convex.dev',
    slogan: 'Reactive backend database for TypeScript apps',
    pricing: 2,
    categories: ['DB', 'Open Source'],
    githubUrl: 'https://github.com/get-convex/convex-backend',
  },
  { name: 'Turso', url: 'https://turso.tech', slogan: 'SQLite databases for production, at the edge', pricing: 2, categories: ['DB'] },
  {
    name: 'Prisma',
    url: 'https://www.prisma.io',
    slogan: 'TypeScript ORM and Postgres hosting',
    pricing: 1,
    categories: ['DB', 'Open Source'],
    githubUrl: 'https://github.com/prisma/prisma',
  },
  // Auth
  {
    name: 'WorkOS',
    url: 'https://workos.com',
    slogan: 'Enterprise SSO, directory sync and auth APIs',
    pricing: 2,
    categories: ['Auth', 'API'],
  },
  {
    name: 'Better Auth',
    url: 'https://www.better-auth.com',
    slogan: 'Open-source authentication framework for TypeScript',
    pricing: 1,
    categories: ['Auth', 'Open Source'],
    githubUrl: 'https://github.com/better-auth/better-auth',
  },
  // Docs
  { name: 'Mintlify', url: 'https://mintlify.com', slogan: 'Developer documentation platform', pricing: 2, categories: ['Docs'] },
  {
    name: 'GitBook',
    url: 'https://www.gitbook.com',
    slogan: 'Docs and knowledge base for technical teams',
    pricing: 2,
    categories: ['Docs'],
  },
  {
    name: 'Docusaurus',
    url: 'https://docusaurus.io',
    slogan: 'Open-source static site generator for docs',
    pricing: 1,
    categories: ['Docs', 'Open Source'],
    githubUrl: 'https://github.com/facebook/docusaurus',
  },
  // Testing
  {
    name: 'Playwright',
    url: 'https://playwright.dev',
    slogan: 'End-to-end testing for modern web apps',
    pricing: 1,
    categories: ['Testing', 'Open Source'],
    githubUrl: 'https://github.com/microsoft/playwright',
  },
  {
    name: 'Cypress',
    url: 'https://www.cypress.io',
    slogan: 'Browser testing for anything that runs in a browser',
    pricing: 1,
    categories: ['Testing', 'Open Source'],
    githubUrl: 'https://github.com/cypress-io/cypress',
  },
  // Email
  { name: 'Resend', url: 'https://resend.com', slogan: 'Email API for developers', pricing: 2, categories: ['Emails', 'API'] },
  {
    name: 'Postmark',
    url: 'https://postmarkapp.com',
    slogan: 'Transactional email delivery for apps',
    pricing: 2,
    categories: ['Emails', 'API'],
  },
  // Automation
  {
    name: 'Zapier',
    url: 'https://zapier.com',
    slogan: 'No-code automation across thousands of apps',
    pricing: 2,
    categories: ['Workflow automation', 'NoCode'],
  },
  {
    name: 'Make',
    url: 'https://www.make.com',
    slogan: 'Visual automation platform for workflows',
    pricing: 2,
    categories: ['Workflow automation', 'NoCode'],
  },
  // AI agents
  {
    name: 'LlamaIndex',
    url: 'https://www.llamaindex.ai',
    slogan: 'Framework for LLM apps and agents over your data',
    pricing: 1,
    categories: ['AI Agents', 'Framework', 'Open Source'],
    githubUrl: 'https://github.com/run-llama/llama_index',
  },
  {
    name: 'Mastra',
    url: 'https://mastra.ai',
    slogan: 'TypeScript framework for AI agents',
    pricing: 1,
    categories: ['AI Agents', 'Framework', 'Open Source'],
    githubUrl: 'https://github.com/mastra-ai/mastra',
  },
  {
    name: 'AI SDK',
    url: 'https://ai-sdk.dev',
    slogan: "Vercel's TypeScript toolkit for AI apps and agents",
    pricing: 1,
    categories: ['AI Agents', 'Framework', 'Open Source'],
    githubUrl: 'https://github.com/vercel/ai',
  },
  // UI, frameworks, CMS
  {
    name: 'Material UI',
    url: 'https://mui.com',
    slogan: 'React components implementing Material Design',
    pricing: 1,
    categories: ['UI Library', 'Open Source'],
    githubUrl: 'https://github.com/mui/material-ui',
  },
  {
    name: 'Next.js',
    url: 'https://nextjs.org',
    slogan: 'The React framework for the web',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/vercel/next.js',
  },
  {
    name: 'Strapi',
    url: 'https://strapi.io',
    slogan: 'Open-source headless CMS',
    pricing: 1,
    categories: ['CMS', 'Open Source'],
    githubUrl: 'https://github.com/strapi/strapi',
  },
  {
    name: 'Sanity',
    url: 'https://www.sanity.io',
    slogan: 'Content platform with a customizable headless CMS',
    pricing: 2,
    categories: ['CMS'],
  },
  // Batch 3 (2026-10-01): peers for frameworks and IaC, more AI coding, hosting, CMS, no-code, testing, runtimes
  // Frameworks
  {
    name: 'Remix',
    url: 'https://remix.run',
    slogan: 'Full-stack web framework built on web standards',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/remix-run/remix',
  },
  {
    name: 'Astro',
    url: 'https://astro.build',
    slogan: 'Web framework for content-driven websites',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/withastro/astro',
  },
  {
    name: 'SvelteKit',
    url: 'https://svelte.dev',
    slogan: 'Svelte framework for building web apps',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/sveltejs/kit',
  },
  {
    name: 'Nuxt',
    url: 'https://nuxt.com',
    slogan: 'Full-stack framework for Vue',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/nuxt/nuxt',
  },
  // Infrastructure as code
  {
    name: 'Pulumi',
    url: 'https://www.pulumi.com',
    slogan: 'Infrastructure as code in TypeScript, Python, Go and more',
    pricing: 1,
    categories: ['DevOps', 'Open Source'],
    githubUrl: 'https://github.com/pulumi/pulumi',
  },
  {
    name: 'OpenTofu',
    url: 'https://opentofu.org',
    slogan: 'Open-source infrastructure as code, a fork of Terraform',
    pricing: 1,
    categories: ['DevOps', 'Open Source'],
    githubUrl: 'https://github.com/opentofu/opentofu',
  },
  // AI coding
  {
    name: 'Amazon Q Developer',
    url: 'https://aws.amazon.com/q/developer/',
    slogan: "AWS's AI assistant for building and operating software",
    pricing: 2,
    categories: ['AI Coding'],
  },
  {
    name: 'Augment Code',
    url: 'https://www.augmentcode.com',
    slogan: 'AI coding agent with deep codebase context',
    pricing: 2,
    categories: ['AI Coding'],
  },
  {
    name: 'Amp',
    url: 'https://ampcode.com',
    slogan: 'Agentic coding tool from Sourcegraph',
    pricing: 2,
    categories: ['AI Coding', 'AI Agents'],
  },
  {
    name: 'Qodo',
    url: 'https://www.qodo.ai',
    slogan: 'AI code review and test generation',
    pricing: 2,
    categories: ['AI Coding', 'Testing'],
  },
  {
    name: 'Warp',
    url: 'https://www.warp.dev',
    slogan: 'Agentic development environment built on a modern terminal',
    pricing: 2,
    categories: ['AI Coding', 'CLI'],
  },
  {
    name: 'OpenCode',
    url: 'https://opencode.ai',
    slogan: 'Open-source AI coding agent for the terminal',
    pricing: 1,
    categories: ['AI Coding', 'CLI', 'Open Source'],
    githubUrl: 'https://github.com/sst/opencode',
  },
  // Hosting
  {
    name: 'Heroku',
    url: 'https://www.heroku.com',
    slogan: 'Platform as a service to deploy and run apps',
    pricing: 2,
    categories: ['Hosting'],
  },
  {
    name: 'DigitalOcean',
    url: 'https://www.digitalocean.com',
    slogan: 'Cloud for developers: droplets, databases and app hosting',
    pricing: 2,
    categories: ['Hosting', 'DevOps'],
  },
  // APIs, data, messaging
  {
    name: 'Redis',
    url: 'https://redis.io',
    slogan: 'In-memory data store for caching, queues and real-time apps',
    pricing: 2,
    categories: ['DB'],
  },
  { name: 'Algolia', url: 'https://www.algolia.com', slogan: 'Search and discovery API', pricing: 2, categories: ['API'] },
  {
    name: 'Twilio',
    url: 'https://www.twilio.com',
    slogan: 'APIs for SMS, voice, email and verification',
    pricing: 2,
    categories: ['API', 'Emails'],
  },
  // CMS
  {
    name: 'Contentful',
    url: 'https://www.contentful.com',
    slogan: 'Headless content platform for digital teams',
    pricing: 2,
    categories: ['CMS'],
  },
  {
    name: 'Payload',
    url: 'https://payloadcms.com',
    slogan: 'Open-source Next.js-native headless CMS',
    pricing: 1,
    categories: ['CMS', 'Open Source'],
    githubUrl: 'https://github.com/payloadcms/payload',
  },
  // No-code, internal tools, design
  { name: 'Retool', url: 'https://retool.com', slogan: 'Build internal tools on top of your data', pricing: 2, categories: ['NoCode'] },
  { name: 'Bubble', url: 'https://bubble.io', slogan: 'Build web and mobile apps without code', pricing: 2, categories: ['NoCode'] },
  {
    name: 'Webflow',
    url: 'https://webflow.com',
    slogan: 'Visual website builder and CMS',
    pricing: 2,
    categories: ['NoCode', 'Visual editing'],
  },
  {
    name: 'Framer',
    url: 'https://www.framer.com',
    slogan: 'Design and publish websites visually',
    pricing: 2,
    categories: ['NoCode', 'Design', 'Visual editing'],
  },
  { name: 'Figma', url: 'https://www.figma.com', slogan: 'Collaborative interface design tool', pricing: 2, categories: ['Design'] },
  // Testing
  {
    name: 'Storybook',
    url: 'https://storybook.js.org',
    slogan: 'Build, test and document UI components in isolation',
    pricing: 1,
    categories: ['UI Library', 'Testing', 'Open Source'],
    githubUrl: 'https://github.com/storybookjs/storybook',
  },
  {
    name: 'Vitest',
    url: 'https://vitest.dev',
    slogan: 'Fast unit testing framework powered by Vite',
    pricing: 1,
    categories: ['Testing', 'Open Source'],
    githubUrl: 'https://github.com/vitest-dev/vitest',
  },
  {
    name: 'Jest',
    url: 'https://jestjs.io',
    slogan: 'JavaScript testing framework',
    pricing: 1,
    categories: ['Testing', 'Open Source'],
    githubUrl: 'https://github.com/jestjs/jest',
  },
  // Runtimes
  {
    name: 'Bun',
    url: 'https://bun.sh',
    slogan: 'Fast JavaScript runtime, bundler, test runner and package manager',
    pricing: 1,
    categories: ['Language', 'Open Source'],
    githubUrl: 'https://github.com/oven-sh/bun',
  },
  {
    name: 'Deno',
    url: 'https://deno.com',
    slogan: 'Secure runtime for JavaScript and TypeScript',
    pricing: 1,
    categories: ['Language', 'Open Source'],
    githubUrl: 'https://github.com/denoland/deno',
  },
  // Batch 4: peers for listings that had none (search, comms, internal tools, design) and big gaps
  {
    name: 'Typesense',
    url: 'https://typesense.org',
    slogan: 'Open source, typo-tolerant search engine',
    pricing: 1,
    categories: ['API', 'Open Source'],
    githubUrl: 'https://github.com/typesense/typesense',
  },
  {
    name: 'Meilisearch',
    url: 'https://www.meilisearch.com',
    slogan: 'Open source search engine with a simple API',
    pricing: 1,
    categories: ['API', 'Open Source'],
    githubUrl: 'https://github.com/meilisearch/meilisearch',
  },
  {
    name: 'Elasticsearch',
    url: 'https://www.elastic.co/elasticsearch',
    slogan: 'Distributed search and analytics engine',
    pricing: 2,
    categories: ['API', 'DB'],
  },
  { name: 'Vonage', url: 'https://www.vonage.com/communications-apis/', slogan: 'APIs for SMS, voice, video and verification', pricing: 2, categories: ['API'] },
  { name: 'SendGrid', url: 'https://sendgrid.com', slogan: 'Email delivery API and marketing email', pricing: 2, categories: ['Emails', 'API'] },
  { name: 'Mailgun', url: 'https://www.mailgun.com', slogan: 'Email API for sending, receiving and tracking email', pricing: 2, categories: ['Emails', 'API'] },
  {
    name: 'Sentry.io',
    url: 'https://sentry.io',
    slogan: 'Error tracking and performance monitoring for developers',
    pricing: 2,
    categories: ['Monitoring'],
    githubUrl: 'https://github.com/getsentry/sentry',
  },
  { name: 'Kinde', url: 'https://kinde.com', slogan: 'Auth, feature flags and billing for SaaS', pricing: 2, categories: ['Auth'] },
  {
    name: 'Drizzle ORM',
    url: 'https://orm.drizzle.team',
    slogan: 'Headless TypeScript ORM for SQL databases',
    pricing: 1,
    categories: ['DB', 'Open Source'],
    githubUrl: 'https://github.com/drizzle-team/drizzle-orm',
  },
  { name: 'Upstash', url: 'https://upstash.com', slogan: 'Serverless Redis, vector and queues', pricing: 2, categories: ['DB'] },
  // AI models and local AI
  {
    name: 'Ollama',
    url: 'https://ollama.com',
    slogan: 'Run open language models locally',
    pricing: 1,
    categories: ['AI', 'CLI', 'Open Source'],
    githubUrl: 'https://github.com/ollama/ollama',
  },
  { name: 'OpenRouter', url: 'https://openrouter.ai', slogan: 'One API for hundreds of AI models', pricing: 2, categories: ['AI', 'API'] },
  { name: 'Hugging Face', url: 'https://huggingface.co', slogan: 'Hub for open AI models, datasets and demos', pricing: 1, categories: ['AI'] },
  // AI coding
  { name: 'Kiro', url: 'https://kiro.dev', slogan: 'Agentic IDE with spec-driven development, from AWS', pricing: 2, categories: ['AI Coding', 'IDE'] },
  {
    name: 'Visual Studio Code',
    url: 'https://code.visualstudio.com',
    slogan: 'Free, open source code editor from Microsoft',
    pricing: 1,
    categories: ['IDE', 'Open Source'],
    githubUrl: 'https://github.com/microsoft/vscode',
  },
  // UI frameworks
  {
    name: 'React',
    url: 'https://react.dev',
    slogan: 'JavaScript library for building user interfaces',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/facebook/react',
  },
  {
    name: 'Vue.js',
    url: 'https://vuejs.org',
    slogan: 'Progressive JavaScript framework for web UIs',
    pricing: 1,
    categories: ['Framework', 'Open Source'],
    githubUrl: 'https://github.com/vuejs/core',
  },
  // Design and internal tools
  {
    name: 'Penpot',
    url: 'https://penpot.app',
    slogan: 'Open source design and prototyping platform',
    pricing: 1,
    categories: ['Design', 'Open Source'],
    githubUrl: 'https://github.com/penpot/penpot',
  },
  {
    name: 'Appsmith',
    url: 'https://www.appsmith.com',
    slogan: 'Open source platform to build internal tools',
    pricing: 1,
    categories: ['NoCode', 'Open Source'],
    githubUrl: 'https://github.com/appsmithorg/appsmith',
  },
  {
    name: 'ToolJet',
    url: 'https://www.tooljet.com',
    slogan: 'Open source low-code platform for internal tools',
    pricing: 1,
    categories: ['NoCode', 'Open Source'],
    githubUrl: 'https://github.com/ToolJet/ToolJet',
  },
];
